---
- name: Install office
  become: true
  when:
    - desktop_environment_office or 'office' in ansible_run_tags
  block:
    - name: Install office | Install office packages
      ansible.builtin.apt:
        name: "{{ _all_office_packages | flatten }}"
        state: present
      vars:
        _all_office_packages:
          - "{{ desktop_environment_spelling_packages }}"
          - "{{ desktop_environment_office_packages }}"

    - name: Install office | Deleting downloaded packages that are no longer required
      ansible.builtin.apt:
        clean: true
