---
- name: Rewrite /etc/network/interfaces
  when:
    - desktop_environment_reconfigure_network
  become: true
  ansible.builtin.template:
    src: etc/network/interfaces.tmpl
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: "0644"
    backup: true
